on: [push]

jobs:
  cognition-deploy:
    runs-on: ubuntu-latest
    name: Deploy experiment to Cognition
    steps:
      - uses: actions/checkout@v3
      - uses: javidalpe/cognition-deploy-action@v1.1.2
        id: deploy
        with:
          personal-access-token: I3rJh7kSY3jrWwjme14vkgzdK6Znl8UjOqCjoAbN
      - run: echo "The public link to the task is ${{ steps.deploy.outputs.link }}"
